source 'https://rubygems.org'

gem 'activerecord', '~> 5.0'
gem 'config'
gem 'database_cleaner'
gem 'factory_bot'
gem 'fuubar'
gem 'httpclient'
gem 'mysql2'
gem 'nokogiri'
gem 'pronto'
gem 'pronto-rubocop', require: false
gem 'pry'
gem 'rake'
gem 'rspec'
gem 'rspec-power_assert'
gem 'rubocop'
gem 'rubocop-performance'
gem 'rugged', '~> 0.28.0'
