source 'https://rubygems.org'

gem 'activerecord'
gem 'config'
gem 'database_cleaner'
gem 'factory_bot_rails'
gem 'fuubar'
gem 'httpclient'
gem 'mysql2'
gem 'nokogiri'
gem 'pronto'
gem 'pronto-rubocop', require: false
gem 'pry'
gem 'rake'
gem 'rspec-power_assert'
gem 'rspec-rails'
gem 'rubocop'
gem 'rubocop-performance'
