url: 'https://db.netkeiba.com'

path:
  race_list: '/race/list'
  race: '/race'
  horse: '/horse'

mysql:
  adapter: 'mysql2'
  database:
    development: 'denebola'
    test: 'denebola_test'
  host: 'localhost'
  username: 'root'
  password: '7QiSlC?4'

backup_dir:
  race_list: 'race_list'
  race: 'races'
  horse: 'horses'

logger:
  level: 'debug'
  time_format: '%Y/%m/%d %H:%M:%S.%6N'
  path:
    database: 'log/database.log'
    collect: 'log/collect.log'
    extract: 'log/extract.log'
    aggregate: 'log/aggregate.log'
