url: 'http://db.netkeiba.com'

path:
  race_list: '/race/list'
  race: '/race'
  horse: '/horse'

mysql:
  adapter: 'mysql2'
  database: 'denebola'
  host: 'localhost'
  username: 'root'
  password: '7QiSlC?4'

backup_dir:
  race_list: 'race_list'
  race: 'races'
  horse: 'horses'
