CREATE TABLE IF NOT EXISTS races (
  id INTEGER AUTO_INCREMENT PRIMARY KEY,
  track VARCHAR(6) NOT NULL,
  direction VARCHAR(2) NOT NULL,
  distance INTEGER NOT NULL,
  weather VARCHAR(6) NOT NULL,
  place VARCHAR(16) NOT NULL,
  round INTEGER NOT NULL
)
